"use client"

import React from "react"
import { CommentSection } from "react-comments-section"

import "react-comments-section/dist/index.css"

const DefaultCommentSection = ({ item }: { item: string }) => {
  const data = [
    {
      productID: "Shrimp-and-Chorizo-Paella",
      comments: [
        {
          userId: "01a",
          comId: "001",
          fullName: "Alice",
          userProfile: "https://www.linkedin.com/in/alice-example/",
          text: "The shrimp and chorizo paella was bursting with flavor!",
          timestamp: "2024-09-28T10:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Alice&background=random",
          replies: [],
        },
        {
          userId: "02b",
          comId: "002",
          fullName: "Bob",
          userProfile: "https://www.linkedin.com/in/bob-example/",
          text: "Loved the smoky taste of the chorizo in the paella.",
          timestamp: "2024-09-28T10:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Bob&background=random",
          replies: [],
        },
        {
          userId: "03c",
          comId: "003",
          fullName: "Charlie",
          userProfile: "https://www.linkedin.com/in/charlie-example/",
          text: "Perfectly cooked shrimp and delicious saffron rice.",
          timestamp: "2024-09-28T11:00:00Z",
          avatarUrl:
            "https://ui-avatars.com/api/name=Charlie&background=random",
          replies: [],
        },
        {
          userId: "04d",
          comId: "004",
          fullName: "Diana",
          userProfile: "https://www.linkedin.com/in/diana-example/",
          text: "A delightful Spanish classic, will order again!",
          timestamp: "2024-09-28T11:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Diana&background=random",
          replies: [],
        },
        {
          userId: "05e",
          comId: "005",
          fullName: "Eve",
          userProfile: "https://www.linkedin.com/in/eve-example/",
          text: "The best paella I've had in a long time.",
          timestamp: "2024-09-28T12:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Eve&background=random",
          replies: [],
        },
      ],
    },
    {
      productID: "Spaghetti-Carbonara",
      comments: [
        {
          userId: "06f",
          comId: "006",
          fullName: "Frank",
          userProfile: "https://www.linkedin.com/in/frank-example/",
          text: "The spaghetti carbonara was creamy and delicious!",
          timestamp: "2024-09-28T12:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Frank&background=random",
          replies: [],
        },
        {
          userId: "07g",
          comId: "007",
          fullName: "Grace",
          userProfile: "https://www.linkedin.com/in/grace-example/",
          text: "Loved the crispy pancetta in the carbonara.",
          timestamp: "2024-09-28T13:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Grace&background=random",
          replies: [],
        },
        {
          userId: "08h",
          comId: "008",
          fullName: "Hank",
          userProfile: "https://www.linkedin.com/in/hank-example/",
          text: "Perfect balance of flavors in the carbonara sauce.",
          timestamp: "2024-09-28T13:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Hank&background=random",
          replies: [],
        },
        {
          userId: "09i",
          comId: "009",
          fullName: "Ivy",
          userProfile: "https://www.linkedin.com/in/ivy-example/",
          text: "A simple yet indulgent dish, highly recommend!",
          timestamp: "2024-09-28T14:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Ivy&background=random",
          replies: [],
        },
        {
          userId: "10j",
          comId: "010",
          fullName: "Jack",
          userProfile: "https://www.linkedin.com/in/jack-example/",
          text: "The best carbonara I've ever tasted.",
          timestamp: "2024-09-28T14:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Jack&background=random",
          replies: [],
        },
      ],
    },
    {
      productID: "Margherita-Pizza",
      comments: [
        {
          userId: "11k",
          comId: "011",
          fullName: "Kate",
          userProfile: "https://www.linkedin.com/in/kate-example/",
          text: "The Margherita pizza was baked to perfection!",
          timestamp: "2024-09-28T15:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Kate&background=random",
          replies: [],
        },
        {
          userId: "12l",
          comId: "012",
          fullName: "Leo",
          userProfile: "https://www.linkedin.com/in/leo-example/",
          text: "Loved the fresh tomatoes and mozzarella on the pizza.",
          timestamp: "2024-09-28T15:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Leo&background=random",
          replies: [],
        },
        {
          userId: "13m",
          comId: "013",
          fullName: "Mia",
          userProfile: "https://www.linkedin.com/in/mia-example/",
          text: "A classic pizza with balanced flavors, so good!",
          timestamp: "2024-09-28T16:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Mia&background=random",
          replies: [],
        },
        {
          userId: "14n",
          comId: "014",
          fullName: "Noah",
          userProfile: "https://www.linkedin.com/in/noah-example/",
          text: "The crust was crispy and delicious.",
          timestamp: "2024-09-28T16:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Noah&background=random",
          replies: [],
        },
        {
          userId: "15o",
          comId: "015",
          fullName: "Olivia",
          userProfile: "https://www.linkedin.com/in/olivia-example/",
          text: "Best Margherita pizza I've had in a while.",
          timestamp: "2024-09-28T17:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Olivia&background=random",
          replies: [],
        },
      ],
    },
    {
      productID: "Chicken-Tikka-Masala",
      comments: [
        {
          userId: "16p",
          comId: "016",
          fullName: "Paul",
          userProfile: "https://www.linkedin.com/in/paul-example/",
          text: "The chicken tikka masala was rich and flavorful!",
          timestamp: "2024-09-28T17:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Paul&background=random",
          replies: [],
        },
        {
          userId: "17q",
          comId: "017",
          fullName: "Quinn",
          userProfile: "https://www.linkedin.com/in/quinn-example/",
          text: "Loved the creamy tomato sauce with aromatic spices.",
          timestamp: "2024-09-28T18:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Quinn&background=random",
          replies: [],
        },
        {
          userId: "18r",
          comId: "018",
          fullName: "Rachel",
          userProfile: "https://www.linkedin.com/in/rachel-example/",
          text: "Tender chicken pieces in a delicious sauce.",
          timestamp: "2024-09-28T18:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Rachel&background=random",
          replies: [],
        },
        {
          userId: "19s",
          comId: "019",
          fullName: "Sam",
          userProfile: "https://www.linkedin.com/in/sam-example/",
          text: "A perfect fusion of Indian and British flavors.",
          timestamp: "2024-09-28T19:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Sam&background=random",
          replies: [],
        },
        {
          userId: "20t",
          comId: "020",
          fullName: "Tina",
          userProfile: "https://www.linkedin.com/in/tina-example/",
          text: "Best chicken tikka masala I've ever had.",
          timestamp: "2024-09-28T19:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Tina&background=random",
          replies: [],
        },
      ],
    },
    {
      productID: "Sushi-Platter",
      comments: [
        {
          userId: "01a",
          comId: "023",
          fullName: "Alice",
          userProfile: "https://www.linkedin.com/in/alice-johnson-123456/",
          text: "The sushi platter was fresh and delicious!",
          timestamp: "2024-09-28T14:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Alice&background=random",
          replies: [],
        },
        {
          userId: "02b",
          comId: "024",
          fullName: "Bob",
          userProfile: "https://www.linkedin.com/in/bob-smith-654321/",
          text: "Loved the variety of nigiri, sashimi, and rolls.",
          timestamp: "2024-09-28T14:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Bob&background=random",
          replies: [],
        },
        {
          userId: "03c",
          comId: "025",
          fullName: "Charlie",
          userProfile: "https://www.linkedin.com/in/charlie-brown-789012/",
          text: "A delightful mix of flavors and textures.",
          timestamp: "2024-09-28T15:00:00Z",
          avatarUrl:
            "https://ui-avatars.com/api/name=Charlie&background=random",
          replies: [],
        },
        {
          userId: "04d",
          comId: "026",
          fullName: "Diana",
          userProfile: "https://www.linkedin.com/in/diana-wilson-901234/",
          text: "Perfect for sushi enthusiasts, highly recommend!",
          timestamp: "2024-09-28T15:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Diana&background=random",
          replies: [],
        },
        {
          userId: "05e",
          comId: "027",
          fullName: "Ethan",
          userProfile: "https://www.linkedin.com/in/ethan-jones-345678/",
          text: "Best sushi platter I've had in a long time.",
          timestamp: "2024-09-28T16:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Ethan&background=random",
          replies: [],
        },
      ],
    },
    {
      productID: "Tacos-al-Pastor",
      comments: [
        {
          userId: "06f",
          comId: "028",
          fullName: "Fiona",
          userProfile: "https://www.linkedin.com/in/fiona-miller-567890/",
          text: "The tacos al pastor were authentic and delicious!",
          timestamp: "2024-09-28T16:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Fiona&background=random",
          replies: [],
        },
        {
          userId: "07g",
          comId: "029",
          fullName: "George",
          userProfile: "https://www.linkedin.com/in/george-clark-678901/",
          text: "Loved the marinated pork and pineapple topping.",
          timestamp: "2024-09-28T17:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=George&background=random",
          replies: [],
        },
        {
          userId: "08h",
          comId: "030",
          fullName: "Hannah",
          userProfile: "https://www.linkedin.com/in/hannah-lee-789012/",
          text: "A deliciously authentic taco experience.",
          timestamp: "2024-09-28T17:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Hannah&background=random",
          replies: [],
        },
        {
          userId: "09i",
          comId: "031",
          fullName: "Ian",
          userProfile: "https://www.linkedin.com/in/ian-walker-890123/",
          text: "Perfectly cooked pork with fresh cilantro and onions.",
          timestamp: "2024-09-28T18:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Ian&background=random",
          replies: [],
        },
        {
          userId: "10j",
          comId: "032",
          fullName: "Julia",
          userProfile: "https://www.linkedin.com/in/julia-king-901234/",
          text: "Best tacos al pastor I've ever tasted.",
          timestamp: "2024-09-28T18:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Julia&background=random",
          replies: [],
        },
      ],
    },
    {
      productID: "Beef-Wellington",
      comments: [
        {
          userId: "11k",
          comId: "033",
          fullName: "Kevin",
          userProfile: "https://www.linkedin.com/in/kevin-harris-123456/",
          text: "The beef wellington was tender and flavorful!",
          timestamp: "2024-09-28T19:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Kevin&background=random",
          replies: [],
        },
        {
          userId: "12l",
          comId: "034",
          fullName: "Laura",
          userProfile: "https://www.linkedin.com/in/laura-martin-234567/",
          text: "Loved the mushrooms and prosciutto wrapping.",
          timestamp: "2024-09-28T19:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Laura&background=random",
          replies: [],
        },
        {
          userId: "13m",
          comId: "035",
          fullName: "Mike",
          userProfile: "https://www.linkedin.com/in/mike-robinson-345678/",
          text: "A stunning main dish, highly recommend!",
          timestamp: "2024-09-28T20:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Mike&background=random",
          replies: [],
        },
        {
          userId: "14n",
          comId: "036",
          fullName: "Nina",
          userProfile: "https://www.linkedin.com/in/nina-thompson-456789/",
          text: "Perfectly baked golden puff pastry.",
          timestamp: "2024-09-28T20:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Nina&background=random",
          replies: [],
        },
        {
          userId: "15o",
          comId: "037",
          fullName: "Oscar",
          userProfile: "https://www.linkedin.com/in/oscar-wright-567890/",
          text: "Best beef wellington I've had in a while.",
          timestamp: "2024-09-28T21:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Oscar&background=random",
          replies: [],
        },
      ],
    },
    {
      productID: "Chocolate-Lava-Cake",
      comments: [
        {
          userId: "16p",
          comId: "038",
          fullName: "Paul",
          userProfile: "https://www.linkedin.com/in/paul-evans-678901/",
          text: "The chocolate lava cake was decadent and delicious!",
          timestamp: "2024-09-28T21:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Paul&background=random",
          replies: [],
        },
        {
          userId: "17q",
          comId: "039",
          fullName: "Quinn",
          userProfile: "https://www.linkedin.com/in/quinn-baker-789012/",
          text: "Loved the molten center that oozes out.",
          timestamp: "2024-09-28T22:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Quinn&background=random",
          replies: [],
        },
        {
          userId: "18r",
          comId: "040",
          fullName: "Rachel",
          userProfile: "https://www.linkedin.com/in/rachel-adams-890123/",
          text: "Perfect with a scoop of vanilla ice cream.",
          timestamp: "2024-09-28T22:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Rachel&background=random",
          replies: [],
        },
        {
          userId: "19s",
          comId: "041",
          fullName: "Sam",
          userProfile: "https://www.linkedin.com/in/sam-carter-901234/",
          text: "A chocolate lover's dream dessert.",
          timestamp: "2024-09-28T23:00:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Sam&background=random",
          replies: [],
        },
        {
          userId: "20t",
          comId: "042",
          fullName: "Tina",
          userProfile: "https://www.linkedin.com/in/tina-davis-012345/",
          text: "Best chocolate lava cake I've ever tasted.",
          timestamp: "2024-09-28T23:30:00Z",
          avatarUrl: "https://ui-avatars.com/api/name=Tina&background=random",
          replies: [],
        },
      ],
    },
  ]

  return (
    <div className="text-black">
      <CommentSection
        currentUser={{
          currentUserId: "01a",
          currentUserImg:
            "https://ui-avatars.com/api/name=Riya&background=random",
          currentUserProfile:
            "https://www.linkedin.com/in/riya-negi-8879631a9/",
          currentUserFullName: "Riya Negi",
        }}
        logIn={{
          onLogin: () => alert("Call login function"),
          signUpLink: "http://localhost:3000/",
        }}
        commentData={data.find((set) => set.productID === item)!.comments}
        placeHolder={"Write a comment..."}
        onSubmitAction={(data) => console.log("check submit,", data)}
        currentData={(data) => {
          console.log("current data", data)
        }}
      />
    </div>
  )
}

export default DefaultCommentSection
